apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: nist-scan-setting-binding
  namespace: openshift-compliance
profiles:
  # Node checks
  - name: rhcos4-moderate
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
  # Platform checks
  - name: ocp4-moderate
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: nist-scan-setting
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
